FROM node:20-slim
ADD . /todo-fe
WORKDIR /todo-fe
ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET $NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ENV NEXTAUTH_URL $NEXTAUTH_URL
ARG NEXT_PUBLIC_API_SERVER_URL
ENV NEXT_PUBLIC_API_SERVER_URL $NEXT_PUBLIC_API_SERVER_URL
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
RUN npm install -g pnpm
RUN pnpm install

EXPOSE 3000

CMD ["node", "server.js"]