import Providers from '@/libs/redux/providers';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import RqProvier from '@/libs/react-query/RqProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    lang: string;
  };
};

console.log('NEXT_PUBLIC_API_SERVER_URL', process.env.NEXT_PUBLIC_API_SERVER_URL);
console.log('MONGODB_URL', process.env.MONGODB_URL);
console.log('GOOGLE_CLIENT_ID', process.env.GOOGLE_CLIENT_ID);
console.log('GOOGLE_CLIENT_SECRET', process.env.GOOGLE_CLIENT_SECRET);
console.log('NEXTAUTH_SECRET', process.env.NEXTAUTH_SECRET);
console.log('NEXTAUTH_URL', process.env.NEXTAUTH_URL);

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <Providers>
      <html lang={params.lang} className="dark">
        <body className={`${inter.className} dark:bg-black`}>
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar
            newestOnTop={false}
            pauseOnFocusLoss={false}
            rtl={false}
            theme="dark"
            pauseOnHover
          />
          <RqProvier>{children}</RqProvier>
        </body>
      </html>
    </Providers>
  );
}
